/**
 * Created by ritesing on 7/28/2015.
 */

storeApp.service('productService',function(){
    return   [
        {
            catName:"Shoes",
            productList:[
                {
                    name:"Shoes1",
                    image:"../img/shoes1.jpg",
                    price:"2200"
                },
                {
                    name:"Shoes2",
                    image:"../img/shoes1.jpg",
                    price:"1999"
                },
                {
                    name:"Shoes3",
                    image:"../img/shoes1.jpg",
                    price:"1235"
                }
            ]
        },
        {
            catName:"Shuttle",
            productList:[
                {
                    name:"Shuttle1",
                    image:"../img/potm.jpg",
                    price:"2800"
                },
                {
                    name:"Shuttle2",
                    image:"../img/potm.jpg",
                    price:"1999"
                },
                {
                    name:"Shuttle3",
                    image:"../img/potm.jpg",
                    price:"1335"
                }
            ]
        },
        {
            catName:"Racket",
            productList:[
                {
                    name:"Ball1",
                    image:"../img/racket.jpg",
                    price:"220"
                },
                {
                    name:"Ball2",
                    image:"../img/racket.jpg",
                    price:"499"
                },
                {
                    name:"Ball3",
                    image:"../img/racket.jpg",
                    price:"335"
                }
            ]
        }

    ]
})